### ISSUE TITLE
Rooms Chat

### ISSUE THREAD

**Issue by cyrilphoenix71** [Jeedom-Plugins-Extra/Jeedom-Plugins-Extra.github.io#2]
Liste des Rooms avec leurs comentaire de titre :

- Standardisation > Template, Docs, Site ... (https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/wiki/IMPERATIFS-avant-publication-d'un-plugin-par-la-Team)

- Customisation > Graphique, JS, Astuces ... (https://github.com/Jeedom-Plugins-Extra/custom-jeedom)

- Developpement > https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/wiki/03-Liste-Plugins-&-Roadmap

- Plugins > Sur le feu : AndroidRemoteControl (https://github.com/Jeedom-Plugins-Extra/plugin-AndroidRemoteControl)

- Présentations > https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/wiki/02---Pr%C3%A9sentation-des-membres-de-la-Team

- Jeedom-Plugins-Extras > Bistro (https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/wiki)

- Domotique > Cablage, Materiel, Scenario

**Comment by cyrilphoenix71** [comment]
@guenneguezt dans le menu setting en haut a droite de Gitter, t'as pas "permissions" ?

**Comment by cyrilphoenix71** [comment]
Plugins je nommerais bien Hot-Plugin en fait non ?

**Comment by guenneguezt** [comment]
Il me faut mon mot de passe github et je le connais pas par cœur pour accéder à permissions.
Pour le chat dédié au plugin, je pense qu'il vaut mieux que le référent du plugin fasse un chat pour le plugin en question. J'éviterai un chat Hot-plugin pour ne pas mélanger les conversations

**Comment by guenneguezt** [comment]
Reste :
•Domotique > Cablage, Materiel, Scenario
•Plugins > Sur le feu : AndroidRemoteControl (https://github.com/Jeedom-Plugins-Extra/plugin-AndroidRemoteControl)
Est-ce que l'on met le premier ?
Personnellement je ne suis pas trop pour. C'est plus quelque chose qui se traite sur le forum officiel Jeedom.

**Comment by cyrilphoenix71** [comment]
Le premier j'y pensais car certes ca fais un peu bistro mais pour un sujet particulier c'est ptre sympa de scinder non ? genre la j'ai un souci de module zwave. Ok pour forum mais ici ya du vrai echange rapide :)

**Comment by cyrilphoenix71** [comment]
Pour le second ca vennait du fait qu'on etait limité en nombre de room, donc on pensais a une room du plugin "en cours"

**Comment by byackee** [comment]
Done
